services:
  postgres:
    image: postgres:18.3-alpine3.23
    container_name: auto-hh-postgres
    hostname: ${POSTGRES_HOST:-postgres}
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DATABASE:-database}
      - PGPORT=${POSTGRES_PORT:-5432}
    expose:
      - ${POSTGRES_PORT:-5432}
    volumes:
      - ./data/postgres/:/var/lib/postgresql/
    shm_size: 128mb
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER:-user}", "-d", "${POSTGRES_DATABASE:-database}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  llm:
    image: ghcr.io/auto-hh/llm:latest
    container_name: auto-hh-llm
    hostname: llm
    environment:
      - BI_ENCODER_NAME=${BI_ENCODER_NAME:-BAAI/bge-m3}
      - BI_ENCODER_TEMPERATURE=${BI_ENCODER_TEMPERATURE:-0.1}
      - CROSS_ENCODER=${CROSS_ENCODER:-BAAI/bge-reranker-v2-m3}
      - FAISS_PATH=${FAISS_PATH:-/faiss_index/}
      - MODEL_PATH=${MODEL_PATH:-}
      - RETRIEVAL_TOP_K=${RETRIEVAL_TOP_K:-50}
      - FINAL_TOP_K=${FINAL_TOP_K:-5}
      - MIN_SCORE=${MIN_SCORE:-0.0}
      - LLM_API_KEY=${LLM_API_KEY:-llm_api_key}
      - LLM_BASE_URL=${LLM_BASE_URL:-https://api.sambanova.ai/v1}
      - LLM_MODEL=${LLM_MODEL:-Qwen3-235B}
      - HF_TOKEN=${HF_TOKEN:-hf_token}
    volumes:
      - ./data/faiss_index/:/app/faiss_index
    expose:
      - 8000
    restart: unless-stopped


  backend:
    # image: ghcr.io/auto-hh/backend:latest
    build:
      context: ../backend/
      dockerfile: ./Dockerfile
    container_name: auto-hh-backend
    hostname: ${BACKEND_HOST:-backend}
    environment:
      - BACKEND_PORT=${BACKEND_PORT:-80}
      - LOG_LEVEL=${LOG_LEVEL:-debug}
      - SECRET_KEY=${SECRET_KEY:-secret_key}
      - JWT_EXPIRATION_DURATION=${JWT_EXPIRATION_DURATION:-24}
      - STATE_EXPIRATION_DURATION=${STATE_EXPIRATION_DURATION:-10}
      - LLM_PATH=${LLM_PATH:-http://llm:8000}
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_HOST=${POSTGRES_HOST:-postgres}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE:-database}
      - CLIENT_ID=${CLIENT_ID:-client_id}
      - CLIENT_SECRET=${CLIENT_SECRET:-client_secret}
      - APP_NAME=${APP_NAME:-app_name}
      - APP_VERSION=${APP_VERSION:-app_version}
      - DEV_CONTACT=${DEV_CONTACT:-dev_contact}
      - REDIRECT_URI=${REDIRECT_URI:-https://api.localhost/auth/complete}
      - SITE_URL=${SITE_URL:-https://localhost/}
    expose:
      - ${BACKEND_PORT:-80}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${BACKEND_PORT:-80}/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    image: ghcr.io/auto-hh/frontend:latest
    container_name: auto-hh-frontend
    hostname: frontend
    environment:
      - BACKEND_HOST=${BACKEND_HOST:-backend}
      - BACKEND_PORT=${BACKEND_PORT:-80}
    ports:
      - 80:80
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped